### ISSUE TITLE
Can't find Nett package on nuget

### ISSUE THREAD

**Issue by origfla** [paiden/Nett#1]
Just want to check if I should be searching under any name other than 'Nett'? Otherwise, any reason it isn't on Nuget...

**Comment by paiden** [comment]
I'm currently fixing the last bits for a (pre) release version. A NuGet package should be available soon.

**Comment by paiden** [comment]
Finally the NuGet packages arrived:
[Nett](https://www.nuget.org/packages/Nett/)
[Nett Strong Named](https://www.nuget.org/packages/Nett.StrongNamed/)
