### ISSUE TITLE
Can using this library in Unity?

### ISSUE THREAD

**Issue by takaaptech** [paiden/Nett#18]
I wonder if this library can include in unity project (v 5.x)?
Thank so much!

**Comment by paiden** [comment]
I'm not 100% sure I understand the question correctly.

You mean that you can use the 'Nett' library in 'Unity'? Do you mean the game engine 'Unity'? 

If so, I have no experience with 'Unity' so I cannot answer the question directly but give you some hints.

'Nett' is a .Net4 (currently full desktop framework) based assembly. So as long as Unity can use such assemblies you should be able to use the library. 

If Unity cannot handle NuGet packages you need to download the NuGet package and extract it to get the assembly (.dll) file.

**Comment by takaaptech** [comment]
Yes i mean unity for making game (https://unity3d.com/)
