### ISSUE TITLE
writing out inline tables

### ISSUE THREAD

**Issue by donvreug** [paiden/Nett#19]
I have a structure as follows:

        public class UserSettings
        {
            public Dictionary<string, Item> VariableProperties { get; set; }
        }
        public class Item
        {
            public bool Checked { get; set; }
            public string Name { get; set; }
            public string Caption { get; set; }
            public string Unit { get; set; }
            public string NumberFormat { get; set; }
            public string Type { get; set; }
            public bool CalcStats { get; set; }
        }

when this is written back to the source toml file it spans multiple lines, e.g.

[User.VariableProperties]

[User.VariableProperties.fe]
Checked = true
Name = "fe"
Caption = "Fe"
Unit = "%"
NumberFormat = "#0.00"
Type = "column"
CalcStats = true

I'll have a number of entries for this table so I was wondering whether is it possible to write this as an inline table to help readability?  e,g,

[User.VariableProperties]
fe = { Checked = true, Name = "fe", Caption = "Fe", Unit = "%", NumberFormat = "#0.00", Type = "column", CalcStats = true }

**Comment by paiden** [comment]
Currently it is not possible to write that inline table. Inline table is currently only supported, where complex CLR types are used as a property directly e.g

```
        public class WithInlineTable
        {
            [TomlInlineTable]
            public InlineTable Table { get; set; }

            public WithInlineTable()
            {
                this.Table = new InlineTable();
            }
        }

        public class InlineTable
        {
            public int Ival { get; set; }
            public string Sval { get; set; }

            public InlineTable()
            {
                this.Ival = 1;
                this.Sval = "x";
            }
        }
```

But treating something inside a list/dict as an inline table is definitely an interesting scenario I didn't think about yet. I hope to support this scenario in the near future.
