### ISSUE TITLE
Version on nuget does not serialize DateTime properly

### ISSUE THREAD

**Issue by petersondrew** [paiden/Nett#3]
The version on nuget serializes DateTime's like so: `02/01/2016 15:40:19 -06:00`
The latest from master serializes DateTime's properly: `2016-02-01T15:40:19.26112-06:00`

**Comment by paiden** [comment]
This was fixed with 2acbc724b73a43a8dbafe6ecace8a29b849cd37d which is not in version 4.0.0 of the NuGetPackage, but in will be in the next one.

**Comment by paiden** [comment]
Release new NuGet package
