### ISSUE TITLE
Error while parsing array with comment

### ISSUE THREAD

**Issue by Splamy** [paiden/Nett#30]
I am using the latest version `v0.6.3` from NuGet.

When parsing a toml file, this construct will fail:
```
"foo" = [
    # Comment
    "bar",
]
```
although similar constructs work fine
```
"foo" = [
    "bar", # Comment after element
    # Comment in emty line
]
```
From what I read in the [specification](https://github.com/toml-lang/toml#user-content-array) I _think_ this should be allowed

Edit: Another thing I just found. This does not work:
```
"foo" = [
    "bar"
]
```
While similar constructs like this do work:
```
"foo" = [ "bar" ]
# or
"foo" = [
    "bar",
]
```

**Comment by gozineha** [comment]
I was testing a custom ahah form which is based on the examples آزمون استخدامی جدید module's autocheckboxes ahah form http://test.gozineha.ir/?a=estekhdami example. Your patch made it live one submission longer compared http://gozineha.ir/ to the sequence in the issue summary. That is: 

1. View form.
 2. Use the ahah element that replaces part of form.
 3. Submit form. (and receive validation errors)
 4. Submit form again. (as if fixing errors)
 5. Submit form again. <- without patch this step is skipped
 آزمون آنلاین
