### ISSUE TITLE
Feature request: Support merging in-memory tables

### ISSUE THREAD

**Issue by Phrohdoh** [paiden/Nett#31]
Having the consuming code provide a utf-8 stream of _some sort_ would allow for on-disk, network, in-memory etc instead of forcing files to be read from disk.

**Comment by paiden** [comment]
Ehm what?

**Comment by Phrohdoh** [comment]
Merging only supports reading from disk [as I understand it](https://github.com/paiden/Nett/blob/13ba698fab9626837e1a559b1283fb9c0b47142e/Test/Nett.Coma.Tests/Functional/MergeTests.cs#L36) but allowing a consuming library to merge from other sources (MemoryStream, etc) would be useful.

**Comment by paiden** [comment]
v0.8.0 of Nett.Coma allows to use custom store implementations. By implementing a small interface it should be quite easy to use s stream based TOML stores.
