### ISSUE TITLE
Enable custom converters to prevent writing of a field

### ISSUE THREAD

**Issue by mister-walter** [paiden/Nett#35]
It would be convenient if there was some way for custom type converters to prevent a field of an object from being written, depending on the value of the field itself.

The main use-case I can see for this is allowing writing Nullable types. In this case, if the field is null, it shouldn't be written, but if it is non-null, it should be written.

One option would be to allow converters to define a predicate that takes in the field's value and returns whether or not it should be written. I can write up a quick PR implementing this if you would like.

**Comment by paiden** [comment]
I have to validate this, but I think the behavior you described is exactly how Nett currently works. If a property of an CLR object is null, it will not get serialized at all.

Just to make sure I understand you correctly, could you provide a small code example to describe the problem?
