### ISSUE TITLE
Writing Literal Strings

### ISSUE THREAD

**Issue by SpookyStuff** [paiden/Nett#37]
Hi,

I'm using Nett and i'm writing a config file in C# that will contain windows paths. So, I'm looking to write TOML Literal Strings (enclosed in single quotes) ...

I see this enum, TomlString.TypeOfString.Literal, in the TomlString object but I can't seem to figure out how to use it, or even if I need to use it to write literal strings to the config.

I've testing reading in Literal Strings, and it works just fine....but can't see how to write them to the config file.

Any help would be appreciated.

Thanks

**Comment by paiden** [comment]
At the moment Nett automatically escapes the string that get written to TOML. So currently this will happen
```csharp
class Foo { public string X { get; set ;} = @"C:\somepath\"

var s  = Toml.WriteString(new Foo());

// Will produce
// X = "C:\\somepath\\"
```

Im not happy with this behavior and the next version of Nett primarily focuses on features allowing users to better control how the TOML that gets written should look like. Also I'd like to find better defaults for some things. E.g. I'd like that strings containing '\' get written as literal strings by default. 

Unfortunately, until these new features are implemented you don't have a way to control it for now. Sorry.

**Comment by SpookyStuff** [comment]
Got it. Thanks for the info
