### ISSUE TITLE
Is it possible to ignore case of key names vs properties when reading?

### ISSUE THREAD

**Issue by queil** [paiden/Nett#56]
Hi @paiden,

First I must say this is a fantastic lib. Although I could not find an answer to the above question. Let's say I've got a property:
```
   public string KeyName {get;set;}
```
and a key in my toml
```
keyname = "value"
```

Then when reading the config my property is null. If the case matches it works fine. Is there a bit of TomlSettings I am missing here or it is just not implemented?

**Comment by queil** [comment]
Cool, that's a great news. Thanks.

**Comment by paiden** [comment]
@queil commit [e6c3833](https://github.com/paiden/Nett/commit/e6c383390715884988c5806fc705066ccebf40cc) implements this new feature.

The unit tests should show what the new settings API and the implemented behavior will look like.

I'm really intererested, what you think of the API and if this implementation handles all our use cases.

**Comment by queil** [comment]
@paiden Thanks, I will check it out shortly and give you some feedback.

**Comment by queil** [comment]
@paiden I've browsed through the tests and IMHO the API looks OK. I'll put it into my project soon but it seems it covers my use case. I want my configs to be as simple and as forgiving as possible that's why I've gone for TOML in the first place. Ability to ignore case will make the experience very smooth. Thanks for your work!

**Comment by paiden** [comment]
Released with Nett v0.10.0

**Comment by queil** [comment]
@paiden much appreciated - thanks for your work!
