### ISSUE TITLE
Consider removing Microsoft.AspNetCore from Nett.AspNet

### ISSUE THREAD

**Issue by twaalewijn** [paiden/Nett#72]
The Nett.AspNet package currently has a package reference to the `Microsoft.AspNetCore` meta package.

This means that, when trying to use Nett.AspNett inside console/winforms/wpf/other applications, a lot of excess packages are being pulled in.

Looking at the code I think the only packages being used are part of the Microsoft.Extensions.Configuration library (which is good of course).
Specifically, the [Microsoft.Extensions.Configuration.FileExtensions](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.FileExtensions/) library seems to cover all of the needed references inside the project.

Changing the project to reference `Microsoft.Extensions.Configuration.FileExtensions` directly would make the Nett.AspNet library easier to use in projects besides ASP.NET Core.

**Comment by paiden** [comment]
> This means that, when trying to use Nett.AspNett inside console/winforms/wpf/other applications, a lot of excess packages are being pulled in.

The Nett.AspNet **package** does not specify any Microsoft.* dependencies at the moment - this is a bug BTW - so no additional packages will be pulled. This will be fixed with this issue here.

> Specifically, the Microsoft.Extensions.Configuration.FileExtensions library seems to cover all of the needed references inside the project.

That is correct. I will change the projects package ref to that, and add it as a dependency to the package itself.

> Changing the project to reference Microsoft.Extensions.Configuration.FileExtensions directly would make the Nett.AspNet library easier to use in projects besides ASP.NET Core.

Out of curiosity... Why would you use the package outside of an AspNetCore project?

**Comment by twaalewijn** [comment]
Thank you for your response.

> The Nett.AspNet **package** does not specify any Microsoft.* dependencies at the moment - this is a bug BTW - so no additional packages will be pulled. This will be fixed with this issue here.

Ah I missed the nuspec files in the root directory.
That is my bad sorry.
Since you were using the SDK csproj format I assumed the automatic NuGet package creation was enabled.

This goes off-topic for my original issue but maybe it would be a good idea to move to that system as well since it would take care of adding the references to Microsoft.Extensions.Configuration.FileExtensions and your Nett package automatically.

Because the current nuspec for Nett.AspNett also seems to claim a dependency on Nett version 0.8.0 which should probably be 0.11.1 for the next version according to the release notes.
I could make a PR for this if you agree with it and want me to.

> Out of curiosity... Why would you use the package outside of an AspNetCore project?

I have a bunch of console applications (at home and at work) that allow some settings to be passed through a config file.

To read those settings from the file I use the ConfigurationBuilder and [Microsoft.Extensions.Configuration.Binder](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Binder) package to make the object conversion format agnostic.

The applications currently support [JSON](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json) as the format for the settings file but a user asked if I could add TOML as well.

Which, since I'm using the ConfigurationBuilder and binder, is easy to do with your Nett.AspNett package because I can just look for a toml file, add it to the builder and call bind on it without having to change any other code.

**Comment by twaalewijn** [comment]
@paiden I saw that you moved to automatically building NuGet packages through csproj properties already.
Thanks for making the the extra effort to fix this :+1: .

I'm sure you've also noticed already but since you were building symbol packages before I thought I'd mention that you can still do so by adding this to the csproj file:
```xml
<IncludeSymbols>true</IncludeSymbols>
```
Which will create the *.symbols.nupkg file in the same directory as the regular package.
If you also want to support the use of the official NuGet symbol server you can specify the snupkg format like this:
```xml
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
```
More on this process can be found here: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg 

If you end up not supporting symbols that would be fine with me as well so in that case just ignore this comment.

**Comment by paiden** [comment]
Ah completely forgot about the symbol packages.... I will fix that in a follow up commit. Thx for the info.
