### ISSUE TITLE
Is it possible to detect syntax errors for spelling errors etc?

### ISSUE THREAD

**Issue by anderejd** [paiden/Nett#78]
I'm loading settings from a toml file using `Toml.ReadFile<SomeStructure>` and I would like to detect when the settings file contains property names that are misspelled or in other words when a property in the TOML file doesn't map to any member on `SomeStructure` in this example.

Is this already supported? If not, would you be interested in adding that support or would you accept a PR for this?

**Comment by paiden** [comment]
This was not yet supported. 

The linked commit shows my first idea to implement such a feature. 

The callback approach with the various parameters, should allow some quite flexible error handling, as the user can decide what should happen if a property cannot be mapped (log message, throw exception etc.)

I'd love to hear some feedback on the API.

**Comment by anderejd** [comment]
The suggested solution in the linked commit looks nice! If I understand the new tests correctly then keys on the root object as well as tables will trigger the missing property callback, perfect.

> The callback approach with the various parameters, should allow some quite flexible error handling, as the user can decide what should happen if a property cannot be mapped (log message, throw exception etc.)

This is exactly what I had in mind as the preferred solution 👍

**Comment by anderejd** [comment]
Can we have a 0.13 release soonish or do you want to think about this new feature some more?

**Comment by paiden** [comment]
I hope to release a new version this weekend.

**Comment by paiden** [comment]
Fixed with v0.13.0
