### ISSUE TITLE
Option to treat provider dictionary keys as case-insensitive in Nett.AspNet

### ISSUE THREAD

**Issue by twaalewijn** [paiden/Nett#81]
Currently the dictionary returned by `ProviderDictionaryConverter.ToProviderDictionary` uses case-sensitive key comparision.

This makes sense because, I believe, keys in TOML itself are case-sensitive.

The problem I am encountering however is that I provide the option to read a config file in either JSON, YAML or TOML format and the JSON/YAML libraries I'm using seem to treat keys as case-insensitive by creating their data dictionary with a `StringComparer.OrdinalIgnoreCase` comparer.

This might have to do with the way the configuration binder libraries tries to bind key values to properties.

Consider the following config and binding class:
```json
// JSON
{
  "intOpt": 1,
  "stringOpt": "somestring"
}
```
```toml
// TOML
intOpt = 1
stringOpt = "somestring"
```
```csharp
public class ConfigBindClass
{
    public int IntOpt { get; set; }
    public string StringOpt { get; set; }
}
```

When instructing the binder to bind the above config to ```ConfigBindClass``` it will use reflection on each of the classes properties to figure out which keys to read from the config.

Since it uses the Name of the properties as the keys, in this case those would be ```IntOpt``` and ```StringOpt```.

So somewhere inside the binder code it calls something like this:

```csharp
config.GetSection(property.Name)
// So it tries config.GetSection("IntOpt") and config.GetSection("StringOpt")
```

This returns nothing in ```Nett.AspNet```'s case since the provider dictionary only has values for keys ```intOpt``` and ```stringOpt```.

I wouldn't say that having case-sensitive keys by default is incorrect but since users using a JSON/YAML version of the config for my program are accustomed to using lowercase keys they are always surprised at first when their TOML config isn't being loaded.

So I'd like an option to be able to configure the ```TomlConfigurationProvider``` to load a case-insensitive dictionary with an OrdinalIgnoreCase key comparer instead for consistency with the other providers.

**Comment by paiden** [comment]
Fixed in v0.15.0
