### ISSUE TITLE
[Nett.Coma] Comments don't get persisted when writing values

### ISSUE THREAD

**Issue by GoryMoon** [paiden/Nett#84]
When writing a value to a `Config` all comments are removed when saved.
I've debugged and identified two locations that make this occur.

---
First, the value getting set doesn't get the previous values comments  https://github.com/paiden/Nett/blob/c2f1d3b83835955b674dafa760f6a4a2b3baa32a/Source/Nett.Coma/Config.cs#L115 https://github.com/paiden/Nett/blob/c2f1d3b83835955b674dafa760f6a4a2b3baa32a/Source/Nett.Coma/Path/TPath.KeySegment.cs#L47

---
Second, when a table is cloned in `ConfigStoreWithSource#Load` the comments of the Tables and the comments of the values in the tables are lost. This is because of  `EnsureCorrectRoot` calls `WithRoot` and thus losing the comments.
https://github.com/paiden/Nett/blob/c2f1d3b83835955b674dafa760f6a4a2b3baa32a/Source/Nett.Coma/TomlEx/TomlTableExtensions.cs#L124 https://github.com/paiden/Nett/blob/c2f1d3b83835955b674dafa760f6a4a2b3baa32a/Source/Nett/Types/TomlTable.cs#L281 https://github.com/paiden/Nett/blob/c2f1d3b83835955b674dafa760f6a4a2b3baa32a/Source/Nett/Types/TomlTable.cs#L424

---
Here is a test for this issue that you can test with, it fails on row 62:
https://gist.github.com/GoryMoon/ec92c1d73006a71301c47369720ccd6e

**Comment by paiden** [comment]
Fixed in v0.15.0
