### ISSUE TITLE
Dotted key support w/ generics

### ISSUE THREAD

**Issue by brent-williams** [paiden/Nett#88]
Can anyone confirm whether nett supports dotted keys w/ generics for read/write?  For example the following works fine:

```csharp
    public class foo {
      public int x { get; set; }
    }
    ...
    Toml.ReadFile<foo>("foo.toml")
```
when reading:
```toml
x = 0
```
but fails of course with:
```toml
x.y = 0
```
I expected TomlMember would be the solution i.e.
```csharp
    public class foo {
      [TomlMember(Key = "x.y")]
      public int xy { get; set; }
    }
```
but that instead seems to oriented to a quoted key, along the lines of:
```toml
'x.y' = 0
```
Have looked over nett source and test but still flummoxed as to how to read/read dotted keys while staying within the comfort of generics.  Perhaps nett doesn't support this scenario?  Suggestions appreciated.

**Comment by paiden** [comment]
```csharp
        class foo
        {
            public foox x { get; set; } = new foox();
        }

        class foox
        {
            public int y { get; set; }
        }


        [Fact]
        public void Sample()
        {
            const string Input = "x.y = 42";

            var f = Toml.ReadString<foo>(Input);

            f.x.y.Should().Be(42);
        }
```

HTH

**Comment by brent-williams** [comment]
@paiden thanks for super-quick reply.  That works for read, but doesn't work for write i.e.:

```csharp
                  var g = Toml.WriteString<foo>(f);
```
generates
```
[x]
y = 42
```
I'd like to be able to both read and write `x.y = 42`.  Possible?

**Comment by paiden** [comment]
Currently this is not possible. This is an oversight on my side. I need to extend the TomlSettings mechanism to allow to specify which what should get written as 'dotted' keys.

**Comment by brent-williams** [comment]
Got it, TomlSettings or maybe an attribute above e.g. the foo.x member.  A workaround in meantime for anyone interested is to use TomlMember and post-process the string to remove the single quotes.  Thanks for the clarification.
